<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>LoginParentDOM</name>
   <tag></tag>
   <elementGuidId>318270ad-8925-4261-b3b9-8139d87f0e4a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>book-app[apptitle='BOOKS']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>book-app[apptitle='BOOKS']</value>
   </webElementProperties>
</WebElementEntity>
